from dataclasses import dataclass
from typing import List, Union

from prtg import Icon

from .common import Status


# Immutable class to have autogenerated __hash__() method in order 
# to take advantage of set operations
@dataclass
class Device:
    id: Union[int, None]
    name: str
    host: str
    service_url: str
    priority: int
    tags: List[str]
    location: str
    icon: Union[Icon, None]
    status: Status
    is_active: bool

    # Allow comparison for adapters
    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return (self.id, self.name, self.host, self.service_url, self.priority, self.tags, self.location, self.icon, self.status, self.is_active) == (other.id, other.name, other.host, other.service_url, other.priority, other.tags, other.location, other.icon, other.status, other.is_active)
        return NotImplemented
