from dataclasses import dataclass
from typing import List, Union

from prtg import Icon

from .common import Status

# Immutable class to have autogenerated __hash__() method in order 
# to take advantage of set operations
@dataclass(frozen=True)
class Device:
    id: Union[int, None]
    name: str
    host: str
    service_url: str
    priority: int
    tags: List[str]
    location: str
    icon: Union[Icon, None]
    status: Status
    is_active: bool
