from dataclasses import dataclass
from typing import List, Union

from .common import Status

# Immutable class to have autogenerated __hash__() method in order 
# to take advantage of set operations
@dataclass(frozen=True)
class Group:
    id: Union[int, None]
    name: str
    priority: int
    tags: List[str]
    location: str
    status: Status
    is_active: bool
