apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: reconcile-snow-prtg
  name: reconcile-snow-prtg
  namespace: default
spec:
  selector:
    matchLabels:
      io.kompose.service: reconcile-snow-prtg
  template:
    metadata:
      labels:
        io.kompose.service: reconcile-snow-prtg
    spec:
      containers:
      - env:
        - name: JWT_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: VAULT_ADDR
          value: http://vault.vault:8200
        image: registry.quokka.ninja/ccfs/xsautomate-actions/reconcile-snow-prtg:latest
        imagePullPolicy: Always
        name: reconcile-snow-prtg
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
      imagePullSecrets:
      - name: gitlab-cr
      restartPolicy: Always
      serviceAccountName: vault
  revisionHistoryLimit: 1
