apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xsautomate
  name: xsautomate
  namespace: default
spec:
  selector:
    matchLabels:
      app: xsautomate
  template:
    metadata:
      labels:
        app: xsautomate
    spec:
      containers:
        image: harbor.k3s.quokka.ninja/library/xsautomate:latest
        name: xsautomate
        ports:
        - containerPort: 80
          protocol: TCP
